In [59]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import os
os.getcwd()
os.chdir(r"C:\Users\athar\Downloads")
import scipy
from scipy import stats

import numpy as np
from numpy import random
import pandas as pd
import scipy
from scipy import stats

import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend #heading, referred as label/scale
from pylab import plot, show, title, xlabel, ylabel 

import scipy
from scipy import stats
from scipy.stats import binom,poisson
from scipy.stats import expon
from scipy.stats import norm,t
from scipy.stats import rv_discrete
from scipy.stats import *
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from scipy.stats import chi2
from statsmodels.stats import proportion 
from statsmodels.stats.proportion import proportions_ztest 
from statsmodels.stats import proportion as ssp

In [2]:
df=pd.read_excel('Marks.xlsx')

In [3]:
df.head()

    Subject Trainer  Marks
0  Calculus  Sudeep     65
1  Calculus  Sudeep     75
2  Calculus  Sudeep     86
3  Calculus  Sudeep     82
4  Calculus  Sudeep     75

In [5]:
np.mean(df.Marks)

74.34146341463415

In [14]:
ssw.ztest(df.Marks,value=75,alternative='smaller')

(-0.45109145813319906, 0.32596181689977954)

In [ ]:
#as value of p=0.32596181689977954, which is LoS=0.0.5 so we do not reject null hypothesis

In [12]:
t.ppf(0.05,len(df)-1) #as error is on left side, we calculate 95% Upper bound

1.6838510133356521

In [11]:
np.mean(df.Marks) + 1.6838510133356528 * np.std(df.Marks,ddof=1)/len(df)**0.5

76.79967333325216

In [18]:
xbar=np.mean(df.Marks)
claim=75
sd=np.std(df.Marks,ddof=1)
n=len(df.Marks)

z=(xbar-claim)/(sd/n**0.5)
z

-0.45109145813319895

# How to calculate the lower value that we can be not rejecting the null hypothesis.

In [22]:
norm.cdf(-0.45109145813319895) #Here we fill the value of test statistics. And we get the p-value as the output. 
"""
As for normal distribution calculation, we consider the mean and those value at 0. That's why we only need to give a specific value; 
we don't need to specify the other things. 

"""

0.3259618168997796

In [25]:
"""
Let's take if hypothetically, the average value of this calculation was 72.38, can this be considered as a null hypothesis or not? 

"""
(72.3-claim)/(sd/n**0.5) #We get the test statistics(Z) after this calculation.

-1.8494749783461235

In [26]:
norm.cdf(-1.8494749783461235) #As a value, we are considering on the left-hand side, that's why we calculate CDF, and it gives us the value of P. 
"""
If this value of p is larger than the level of significance, then we do not reject the hypothesis. 
"""

0.032194628794015676

In [29]:
"""
Now, as we want the p-value not to get rejected, we need it to be greater than 0.05. For that reason, we calculate norm.ppf = 0.05. 

"""
norm.ppf(0.05) 
#norm.ppf(0.05)==>-1.6448536269514729
"""
this gives us the p-value
now we reshuffle the Z formula and calculate the value of x in formula
z=(x-mu)/(sigma/n**0.5)
x=z*(sigma/n**0.5)+mu

x=actual mean
mu=expected
sigma=std dev
n=no. of sample test


"""

'\nthis gives us the p-value\nnow we reshuffle the Z formula and calculate the value of x in formula\nz=(x-mu)/(sigma/n**0.5)\nx=z*(sigma/n**0.5)+mu\n\nx=actual mean\nmu=expected\nsigma=std dev\nn=no. of sample test\n\n\n'

In [32]:
-1.6448536269514729*(sd/n**0.5)+75 
"""

"""

72.59872134266969

In [ ]:
"""
So p-value gives you the probability. But before we write this, you can just write this statement. This is assuming when I'm giving this definition of p-value. 
That is assuming the null hypothesis to be true. So we put these words at the end. As a matter of chance variation,
p-value is the probability that the value that you are observing is a matter of chance variation. 
Assuming the null hypothesis to be true. 
"""

In [ ]:
"""

"""

In [46]:
mod1=ols('Marks~Subject',df).fit()

In [88]:
tb1=sm.stats.anova_lm(mod1)
tb1

            df       sum_sq    mean_sq         F    PR(>F)
Subject    2.0    15.158906   7.579453  0.082763  0.920735
Residual  38.0  3480.060606  91.580542       NaN       NaN

This is used to find the Grand Mean.

In [100]:
gm=np.mean(df.Marks)
gm

74.34146341463415

In [99]:
df['TotalVatr']=(df['Marks']-gm)**2 #Square deviation of each point from the grand mean.

In [49]:
df.head()

    Subject Trainer  Marks   TotalVatr
0  Calculus  Sudeep     65   87.262939
1  Calculus  Sudeep     75    0.433670
2  Calculus  Sudeep     86  135.921475
3  Calculus  Sudeep     82   58.653183
4  Calculus  Sudeep     75    0.433670

In [97]:
TotalVariance=sum(df['TotalVatr'])
TotalVariance

3495.2195121951218

Calculating the variance within the sample.

In [98]:
# calculating variance within sample
dfcalc = df[df.Subject=="Calculus"]
dfStats = df[df.Subject=="Statistics"]
dfTrigno= df[df.Subject=="Trigno"]


meanCalc = np.mean(dfcalc.Marks)
meanStats = np.mean(dfStats.Marks)
meanTrigno = np.mean(dfTrigno.Marks)


dfcalc["withinvar"] = (dfcalc["Marks"] - meanCalc)**2
dfStats["withinvar"] = (dfStats["Marks"] - meanStats)**2
dfTrigno["withinvar"] = (dfTrigno["Marks"] - meanTrigno)**2

sum(dfcalc["withinvar"])

sum(dfcalc["withinvar"]) + sum(dfStats["withinvar"]) + sum(dfTrigno["withinvar"])

#3480.060606060606==> this value refers to the residual sum of squares/calculating variance within sample

3480.060606060606

In [90]:
"""
Total variance = variance within sample + variance between samples. 
3495.2195121951218=3480.060606060606+15.158
"""

'\nTotal variance = variance within sample + variance between samples. \n3495.2195121951218=3480.060606060606+15.158\n'

In [91]:
#To manually find variance between samples
"""
The formula is ∑ of elements in each column X (specific mean - grand mean)² 
"""

229.5857373044337

In [96]:
11*(np.mean(dfCalc.Marks)-gm)**2 + 15*(np.mean(dfStats.Marks)-gm)**2 + 15*(np.mean(dfTrigno.Marks)-gm)**2

13.974092140921183

In [ ]:
"""
As there are three subjects, we do 3 -1 to get the degree of freedom 2, which is inserted at subjects -DF. 
41 rows of data. For this 41 rows of data, the total amount of degrees of freedom will be 41 - 1 = 40.
Out of these 40 degrees of freedom, 
you have already given 2 to the subject. How many left? 38. 
"""

In [105]:
"""
To find the final p-value, we use SF of F. We enter the values of subjects F, the value of subject df, and residual df. 
We use sf as we are calculating variance and it should be positive, so that's why right? 
And in order to calculate the area under right, we use sf. 
"""
f.sf(0.082763,2,38)

0.9207347686569676

In [107]:
print(pairwise_tukeyhsd(df.Marks,df.Subject)) 
"""
only then you are rejecting it because this value is less than 0. Next, what would have happened? One of these values, I am sorry, both these values.
Either both will be negative or both will be positive. In any case, 0 will not fall in that interval. 
What does that mean? That the difference of the averages is not equal to 0. That means they are not equal. That is that is, 
we reject the null hypothesis. 

You can see one observation. If reject is true, then the value of lower and upper both will be either positive or negative.
As the difference of them can't be 0, in the final results, then we reject the hypothesis. 
"""

    Multiple Comparison of Means - Tukey HSD, FWER=0.05
============================================================
  group1     group2   meandiff p-adj   lower   upper  reject
------------------------------------------------------------
  Calculus Statistics   1.5212 0.9156 -7.7434 10.7858  False
  Calculus     Trigno   0.6545 0.9838 -8.6101  9.9192  False
Statistics     Trigno  -0.8667 0.9667 -9.3889  7.6555  False
------------------------------------------------------------

In [108]:
print(pairwise_tukeyhsd(df.Marks,df.Trainer))

Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj  lower   upper  reject
---------------------------------------------------
 Ruchi Sudeep   9.9879 0.0003 4.9039 15.0719   True
---------------------------------------------------

In [117]:
"""What tells me that I have to use ANOVA? That answer should have been there is one variable which is a continuous data, 
and I want to check whether that continuous data depends on the multiple categories. 
For monitoring a continuous data which is getting categorized into multiple categories based on some categorical variable. 
Marks are getting categorized into stats, trigonometric, calculus. Subject is a categorical data. Marks could be categorized on the basis"""

'What tells me that I have to use ANOVA? That answer should have been there is one variable which is a continuous data, \nand I want to check whether that continuous data depends on the multiple categories. \nFor monitoring a continuous data which is getting categorized into multiple categories based on some categorical variable. \nMarks are getting categorized into stats, trigonometric, calculus. Subject is a categorical data. Marks could be categorized on the basis'

# Two way ANOVA.

In [115]:
mod2=ols('Marks~Trainer+Subject',df).fit()

In [116]:
tb2=sm.stats.anova_lm(mod2)
tb2

            df       sum_sq      mean_sq          F    PR(>F)
Trainer    1.0  1007.318546  1007.318546  15.341424  0.000372
Subject    2.0    58.479354    29.239677   0.445319  0.644008
Residual  37.0  2429.421612    65.660044        NaN       NaN

In [ ]:
"""
Null hypothesis for trainers :
will be that all of them have equal marks. 

Null hypothesis for subject:
All the pairs of subjects have almost equal marks; whatever be the difference is a matter of chance variation. 
"""

In [ ]:
#Interaction of factors

In [118]:
#In this case, that interaction between subject and trainer is not significant. This is my null hypothesis in this scenario.
mod1=ols('Marks~Trainer*Subject',df).fit()

In [119]:
tb1=sm.stats.anova_lm(mod1)
tb1
"""
Here, as the value of p is greater than 5%, we do not reject the null hypothesis. 
We can conclude that trainer, dull, and subject have no significance on each other. 
"""

                   df       sum_sq      mean_sq          F    PR(>F)
Trainer           1.0  1007.318546  1007.318546  15.892045  0.000325
Subject           2.0    58.479354    29.239677   0.461302  0.634241
Trainer:Subject   2.0   210.943834   105.471917   1.663987  0.204016
Residual         35.0  2218.477778    63.385079        NaN       NaN

There are two independent samples, the difference of their means has to be compared against the claim values. 
    Again, mean, third paired leaders, the mean difference of the paired values has to be compared against the claim value. 
    Again, mean, 4, 1, 1, 1, over multiple samples, and we want to check whether the averages of all the pairs of means are equal or not. 
Again, means, same way as two-way ANOVA. Multiple samples which can be made on two different or multiple categorical variables, not just one.
    There could be multiple categorical variables, and you want to check whether the means of all combinations are equal or not.
Again, its means, so all the five tools that I've done: one sample t-test, and two-way ANOVA.

# One-sample variance test

"""
here it becomes that the variance of a sample has to be compared against the claim value.
and To establish whether their ratio is statistically significant or not. 
For continuous data 


"""

In [6]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name='faithful')

In [8]:
erupt=df.eruptions

In [ ]:
"""
Minimum value of variance is 1.42. 
H0:var(erupt)>=1.42
Ha:var(erupt)<1.42==> left tail test
"""

In [10]:
ts=(len(erupt)-1)*np.var(erupt,ddof=1)/1.42  #Variance we have ==>np.var(erupt,ddof=1) expected variance==>1.42

In [12]:
ts

248.6192804240885

In [14]:
p_value=chi2.cdf(ts,len(erupt)-1) #We use CDF as its left tail test. 
p_value

0.1684500172251567

In [16]:
np.var(erupt,ddof=1)

1.3027283328494672

In [ ]:
"""
Even the value of variation is less than 1.42 . We need to consider about the chance variation. 
The value of p is greater than LoS. We do not reject the null hypothesis. 
"""

In [ ]:
"""
Maximum value of variance is 1.1. 
H0:var(erupt)<=1.1
Ha:var(erupt)>1.1==> right tail test
"""

In [17]:
ts=(len(erupt)-1)*np.var(erupt,ddof=1)/1.1

In [19]:
p_value=chi2.sf(ts,len(erupt)-1)  #We use SF as its right tail test. 
p_value

0.019972202957899473

In [20]:
"""
In this scenario, we reject the null hypothesis as a value of p is less than LoS. 
So we can conclude that the value of variance is not less than 1.1. 
"""

1.3027283328494672

In [21]:
"""Hypothesis is that the value of erupt is equal to 1.4 or let's make it equal to 1.5, let's see what happens. So now my new hypothesis is 
that the value, this will become a true data, this is equal to 1.5, so this would be not equal to 1.5 and this would be 1.5 and this would be 1.5. 
This is what is happening."""

ts=(len(erupt)-1)*np.var(erupt,ddof=1)/1.5

In [26]:
p1=chi2.cdf(ts,len(erupt)-1)
p1

0.0576626251138189

In [28]:
p2=chi2.sf(ts,len(erupt)-1)
p2

0.9423373748861811

In [29]:
p_value=p1*2 #We select the p_value which is smaller and multiply that by 2 to get the p_value. We do this because p_value can't be greater than 1 as
#probability can't be greater than 1
p_value

0.1153252502276378

Two sample variance test. 
#Ratio of variances of two samples will be compared against the claim value.

In [30]:
s1=erupt[30:75]

In [31]:
s2=erupt[130:185]

In [32]:
np.var(s1,ddof=1)/np.var(s2,ddof=1)

1.1809148363672546

In [ ]:
""" 
Claim that the variance of S1 is at least 1.4 times that of S2. 
H0 var(S1)/var(S2)>=1.4
Ha var(S1)/var(S2)<1.4
"""

In [33]:
ts=(np.var(s1,ddof=1)/np.var(s2,ddof=1))/1.4

In [35]:
p_value=f.cdf(ts,len(s1)-1,len(s2)-1) #We took CDF, and this is a left-tail test. 
p_value

0.28174693256496913

In [47]:
norm.cdf(200,210,7.93)

0.10364829017927402

In [49]:
expon.cdf(3,scale=0.5)

0.9975212478233336

In [51]:
expon.cdf(5,scale=0.5)

0.9999546000702375

"""
Discrete Data Tools 
One sample proportion Test
this test is used to compare the sample proportion against a claimed value and establish whether 
their difference is statistically significant or not. 
 
 """

In [ ]:
#the proportion age of freshers is limited to 70% 
#H0 prop(freshers)<=0.7 Ha prop(freshers)>0.7==> right tailed test
#In the batch of 75 students, there are 56 freshers.

In [61]:
ssp.proportions_ztest(56,75,value=0.7,alternative='larger')
#p_value==>0.17638237987672073
#test result==>0.9292399270937868
"""
As p-value is greater than LoS, we do not reject the Null Hypothesis. 
"""

(0.9292399270937868, 0.17638237987672073)

# 2-Sample Proportion Test :

In [ ]:
 this test is used to compare the difference of two sample proportions against a claim and, 
 at the same time, establish whether the difference between them is statistically significant or not.